### ISSUE TITLE
Not balance padding in course schedule

### ISSUE THREAD

**Issue by nightlan1015297** [abc873693/ap_common#99]
The card shown in the course schedule gets padding at the bottom & right. However, the top & left have no padding and stick to the border directly.

Does it design in this way originally? If not I think this is an issue.

<img src = 'https://user-images.githubusercontent.com/46278533/194741152-fa1bac17-de54-4484-bd74-02d63388e541.png' width=250></img>

Reproduce information :
|description|info|
|:--:|:--:|
|Model|Pixel4|
|Android version|Android 13 (TPB4.220624.008)|
|App name|中山校務通|
|App version|1.2.4 (latest release since 2022 9/14)|

**Comment by abc873693** [comment]
UI reference from google calendar, some padding is better
